name: Deploy to GAS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Clasp
      run: npm install -g @google/clasp

    - name: Authenticate Clasp
      env:
        CLASP_TOKEN: ${{ secrets.CLASP_TOKEN }}
      run: echo "$CLASP_TOKEN" > ~/.clasprc.json

    - name: Deploy to Google Apps Script
      run: clasp push
